### ISSUE TITLE
Cloning Error

### ISSUE THREAD

**Issue by SimonRastikian** [thomwiggers/kemtls-experiment#3]
fatal: reference is not a tree: 0c105a512fb329708ce1dc0d2941240244e0d227
Unable to checkout '0c105a512fb329708ce1dc0d2941240244e0d227' in submodule path 'pqcrypto/pqclean'

I am not sure why this is happening: all the cloning is working well besides pqclean.

Should I clone https://github.com/PQClean/PQClean/ by hand with --recurse-submodules?

**Comment by thomwiggers** [comment]
What branch are you on?

**Comment by SimonRastikian** [comment]
I am on the master branch, using:
git clone --recurse-submodules https://github.com/thomwiggers/kemtls-experiment/

**Comment by thomwiggers** [comment]
I've just cloned the master branch with the following command:

    git clone https://github.com/thomwiggers/kemtls-experiment.git --recurse-submodules

and that worked fine, but may be due to my local git config.

There is a small mistake in the pqcrypto branch, because it should be tracking that commit via https://github.com/thomwiggers/PQClean/commit/0c105a512fb329708ce1dc0d2941240244e0d227, not via the `PQClean/PQClean` repo.

**Comment by thomwiggers** [comment]
Could you `rm -rf kemtls-experiment` and try again with `--recurse-submodules`? I've just pushed 138f1a4

**Comment by SimonRastikian** [comment]
Things are working fine now :) thank you!
I think this issue could be closed
