### ISSUE TITLE
No TLS 1.2 Support

### ISSUE THREAD

**Issue by SimonRastikian** [thomwiggers/kemtls-experiment#6]
Hello,

I was trying to run 
./target/debug/examples/tlsclient --http expired.badssl.com
in  rustls-mio from rustls-kemtls. It seems that the main throws an internal error 
This same error occurs with ./target/debug/examples/tlsclient --http mozilla-modern.badssl.com

Connecting to server for iteration 0 of 1
EMITTED CH: 1591937 ns
RECEIVED SH: 391645551 ns
thread 'main' panicked at 'internal error: entered unreachable code: Don't support TLS 1.2 anymore', /home/simonpc/Documents/kemtls-experiment/rustls-kemtls/src/client/hs.rs:927:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I am not sure how to activate the TLS 1.3 since the problem is arising  from 
// For TLS1.3, start message encryption using
// handshake_traffic_secret.
        if sess.common.is_tls13() {
            validate_server_hello_tls13(sess, server_hello)?;
            self.start_handshake_traffic(sess, server_hello)?;
            emit_fake_ccs(&mut self.handshake, sess);
            return Ok(self.into_expect_tls13_encrypted_extensions());
        }
        unreachable!("Don't support TLS 1.2 anymore");

**Comment by thomwiggers** [comment]
`rustls-kemtls` on master branch only supports KEMTLS, no other protocol. The `reimplementation` branch attempts to preserve older TLS versions (mostly preserving TLS 1.3), but no guarantees. Servers in the wild are also liable to choke on the non-standard codepoints and extensions used.

Can I ask what you're attempting to do, by the way? This implementation is only suitable for research purposes, has no security guarantees and I would not be surprised if it's even subtly incorrect with regards to our own research paper.

**Comment by SimonRastikian** [comment]
I have cloned the master branch, but I am not sure what you mean by it does not support other protocol: all I am trying to do is to run the rustl-mio in rustls-kemtls so I understand how the implementation has been done.
In fact I am a master student who just started my internship project, and I am trying to understand how your implementation works. It could be nice of you (if you have some time) to guide me through the folders and the implementations so that I can have a clearer idea and so I can move faster with my project.
Thank you for your responses and your help :)

**Comment by thomwiggers** [comment]
The `rustls-kemtls` folder only implements KEMTLS — TLS 1.3 support has been broken because it seemed easier at the time. I made big changes to the key schedule and to the message flow to implement (just) KEMTLS without preserving TLS 1.3.

Meanwhile, the `rustls-pqtls` folder integrates post-quantum cryptography in TLS 1.3, giving us a post-quantum variant of TLS 1.3.

The best way of experimenting with these implementations is setting up both a rustls client and server and having those talk to each other. The `Dockerfile` is probably instructive and can help to set up the right environment — see also the https://github.com/thomwiggers/kemtls-experiment/blob/master/measuring/scripts/create-experimental-setup.sh script (you probably need to run it from the `measuring` folder — it's been a little while).

This script will create a folder with the name of the selected primitives and set up `pqtls{server,client}` binaries (post-quantum TLS 1.3) and `kemtls{server,client}` binaries (KEMTLS). It will also setup certificates and keys in that folder.

However, depending on what you want to do, it might be better to have a look at the newer `reimplementation` branch, although that branch is slightly less stable (there's some development work still happening). It might be good to have a talk to see if I can help you, and I'm also very curious about your project. Can you send me an email?

**Comment by SimonRastikian** [comment]
Hello,

My apologies for my late response.
I just sent you an email :)

Best regards

**Comment by thomwiggers** [comment]
Let's continue there as this issue is otherwise answered
